CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE');

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gender" "Gender";
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "excludeFromAlias" BOOLEAN NOT NULL DEFAULT false;
